// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cktwqgdkcecbgrgjgnlt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrdHdxZ2RrY2VjYmdyZ2pnbmx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNTgyMjUsImV4cCI6MjA2NDczNDIyNX0.B8FcpBEhipLTEWbqTuwu818Vs0jfkpqH5fic0BoboJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);